apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: jorgemussato/kub-demo-users:latest
          env:
            - name: AUTH_URL
              # value: '10.105.2.95' # ip do serviço
              # melhor prática é usar esse nome do serviço.
              value: 'auth-service.default' # <service_name>.<namespace>