apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem # ou Block
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # esse volume pode ser montado apenas por um node, mas por vários pods  
    # - ReadOnlyMany # esse volume readonly pode ser usado em vários nodes
    # - ReadWriteMany # esse volume readwrite pode ser usado em vários nodes
  hostPath:
    path: /data
    type: DirectoryOrCreate
