apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi #pode ter várias claims para o mesmo volume, cada um "pede" uma quantidade que não seja maior que a capacidade do volume
